### ISSUE TITLE
kentcdodds.com -> kentcdodds.github.io

### ISSUE THREAD

**Issue by kentcdodds** [SumTotalSystems/kcd-angular#1]
I'm making changes to my website. Please update your URLs referencing `kentcdodds.com` to reference `kentcdodds.github.io` instead. Thanks!

**Comment by mikejr83** [comment]
Hey Kent,

Thanks for the heads up! I tried hitting both URLs and got 404'd. We're referencing http://kentcdodds.com/kcd-angular in our project description and in the README.md. Will the relative path remain the same? If so, I'll just change the host portion and when everything is live on your end we'll be good!

I appreciate you reaching out! We've been loving the heck out of the recompile directive! It's helped a ton with page performance.

**Comment by mikejr83** [comment]
Looks like there was no index.html or something. Quick question, are your components now bower consumable? I started looking at the latest on your repo and got to scratching my head on why we created our own. I asked the guy I was working with and he's scratching his head too. Anyway, thanks for providing some awesome stuff!

**Comment by kentcdodds** [comment]
Looks like it :)
